name: Update README with Random Quote
on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch: 

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm install node-fetch
      - name: Run Script
        run: node quote_generator.mjs
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add README.md
          git commit -m "Updated Quote"
          git push
